# config-repo/application.yml

# #########################################
#       ENV. VARIABLES                    #
# #########################################

# Nom de domaine
DOMAINE_NAME: http://localhost:3000

# Application
APP_NAME: Lawan
APP_URL: ${DOMAINE_NAME}
APP_EMAIL_NOREPLY: no-reply
APP_EMAIL_CONTACT: contact@kodoops.fr
APP_MAIL_VERIFY_HOST: ${DOMAINE_NAME}
APP_MAIL_USERNAME: contact@kodoops.fr
APP_MAIL_SMTP_AUTH: true
APP_MAIL_STARTTLS_ENABLED: true
APP_MAIL_DEBUG: true

# Server Mail
SERVER_MAIL_PROTOCOL: smtp
SERVER_MAIL_HOST: smtp4dev
SERVER_MAIL_PORT: 9025
SERVER_MAIL_USERNAME: ""
SERVER_MAIL_PASSWORD: ""

# #########################################
#       PROPERTIES                        #
# #########################################

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

app:
 security:
   encryption-key: 33c2c2f640048153d6cd7b3f215e1980d8fd4c4e3735ecb
   expiration-time: 86400000

#ZIPKIN
management:
  tracing:
    sampling:
      probability: 1.0
# ACTUATOR
  endpoints:
    web:
      exposure:
        include: health, info  # Expose uniquement les endpoints de santé et d'informations
      base-path: /actuator  # Définit le chemin de base pour les endpoints
  endpoint:
    health:
      show-details: when-authorized  # Affiche les détails uniquement pour les utilisateurs autorisés

#CORS 
cors:
  allowed:
    origins: ${DOMAINE_NAME}

#DEBUG
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE:http://localhost:8761/eureka/}
#     fetchRegistry: true
#     registerWithEureka: true
#   instance:
#     preferIpAddress: true
#     leaseRenewalIntervalInSeconds: 30
#     leaseExpirationDurationInSeconds: 90


app:
  name: ${APP_NAME}
  url: ${DOMAINE_NAME}
  email:
    noreply: ${APP_EMAIL_NOREPLY}
    contact: ${APP_EMAIL_CONTACT}
  mail:
    verify:
      host: ${DOMAINE_NAME}
    username: ${APP_MAIL_USERNAME}



