# config-repo/application-dev.yml
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: ${EUREKA_URL_SERVER:http://localhost:8761/eureka/}

# # CONFIG SERVER URL
# CONFIG_SERVER_URL: http://localhost:8888

# # CORS
# CORS_ALLOWED_ORIGINS: ${DOMAINE_NAME}

# Modifiez ici les adresses et configurations spécifiques au développement local
