spring:
  datasource:
    url: jdbc:${DB_SQL_JDBC}://${DB_SQL_HOST}:${DB_SQL_PORT}/${DB_SQL_DATABASE_NAME}?createDatabaseIfNoExist=true
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: ${DB_SQL_DIALECT}
        format_sql: true
    show-sql: ${DB_SHOW_SQL}
    generate-ddl: true
    open-in-view: false

#EUREKA REGISTRY SERVICE
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL_SERVER}

#APPLICATION
app:
  name: ${APP_NAME}
  url : ${APP_URL}
  mail:
    verify:
      host: ${APP_MAIL_VERIFY_HOST}
    username: ${APP_MAIL_USERNAME}
    # MAIL PROPERTIES
    smtp:
      auth: ${APP_MAIL_SMTP_AUTH}
      starttls.enable: ${APP_MAIL_STARTTLS_ENABLED}
    debug: ${APP_MAIL_DEBUG}
  email:
    noreply: ${APP_EMAIL_NOREPLY}
    contact: ${APP_EMAIL_CONTACT}
  security:
    encryption-key: ${APP_SECURITY_ENCRYPTION_KEY}
    expiration-time: ${APP_SECURITY_EXPIRATION_TIME}
