#SERVER
server:
  port: ${SERVER_PORT:8080}

#SPRING
spring:
  cloud:
    gateway:
      routes:
        - id: timesheets
          uri: lb://SERVICE-TIMESHEET
          predicates:
            - Path=/timesheets/**
            - Path=/sheet/weeks/**
            - Path=/sheet/projects/**
            - Path=/sheet/activities/**
            - Path=/sheet/comments/**
            - Path=/sheet/files/**
        - id: authenticate
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authenticate/**
        - id: collaborators
          uri: lb://SERVICE-COLLABORATORS
          predicates:
            - Path=/collaborators/**